/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author User
 */
public class ConsultarCarton extends javax.swing.JPanel {

    /**
     * Creates new form ConsultarCarton
     */
    public ConsultarCarton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdentificación = new javax.swing.JTextField();
        btMostrar = new javax.swing.JButton();
        btRegresar = new javax.swing.JButton();
        lblCedula = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consultar cartón");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 840, 70));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Identificación:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, 40));

        txtIdentificación.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtIdentificación.setToolTipText("");
        txtIdentificación.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtIdentificaciónActionPerformed(evt);
            }
        });
        add(txtIdentificación, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 300, 40));

        btMostrar.setBackground(new java.awt.Color(102, 102, 102));
        btMostrar.setFont(new java.awt.Font("Viner Hand ITC", 0, 20)); // NOI18N
        btMostrar.setForeground(new java.awt.Color(255, 153, 0));
        btMostrar.setText("Mostrar");
        btMostrar.setActionCommand("1");
        btMostrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 140, -1));

        btRegresar.setBackground(new java.awt.Color(102, 102, 102));
        btRegresar.setFont(new java.awt.Font("Viner Hand ITC", 0, 20)); // NOI18N
        btRegresar.setForeground(new java.awt.Color(255, 153, 0));
        btRegresar.setText("Regresar");
        btRegresar.setActionCommand("0");
        btRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 140, -1));

        lblCedula.setFont(new java.awt.Font("Viner Hand ITC", 1, 30)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(255, 153, 0));
        lblCedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 840, 70));

        lblNombre.setFont(new java.awt.Font("Viner Hand ITC", 1, 30)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 153, 0));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 840, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdentificaciónActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtIdentificaciónActionPerformed
    {//GEN-HEADEREND:event_txtIdentificaciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificaciónActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btMostrar;
    public javax.swing.JButton btRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel lblCedula;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JTextField txtIdentificación;
    // End of variables declaration//GEN-END:variables
}
