/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author User
 */
public class Estadisticas extends javax.swing.JPanel
{

    /**
     * Creates new form Estadisticas
     */
    public Estadisticas()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlGrafoBarras = new javax.swing.JPanel();
        pnlCircularHistorica = new javax.swing.JPanel();
        pnlDateHanding = new javax.swing.JPanel();
        pnlTopCinco = new javax.swing.JPanel();
        btRegresar1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pnlGrafoBarrasLayout = new javax.swing.GroupLayout(pnlGrafoBarras);
        pnlGrafoBarras.setLayout(pnlGrafoBarrasLayout);
        pnlGrafoBarrasLayout.setHorizontalGroup(
            pnlGrafoBarrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlGrafoBarrasLayout.setVerticalGroup(
            pnlGrafoBarrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        add(pnlGrafoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 400, 400));

        javax.swing.GroupLayout pnlCircularHistoricaLayout = new javax.swing.GroupLayout(pnlCircularHistorica);
        pnlCircularHistorica.setLayout(pnlCircularHistoricaLayout);
        pnlCircularHistoricaLayout.setHorizontalGroup(
            pnlCircularHistoricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlCircularHistoricaLayout.setVerticalGroup(
            pnlCircularHistoricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        add(pnlCircularHistorica, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 400, 400));

        javax.swing.GroupLayout pnlDateHandingLayout = new javax.swing.GroupLayout(pnlDateHanding);
        pnlDateHanding.setLayout(pnlDateHandingLayout);
        pnlDateHandingLayout.setHorizontalGroup(
            pnlDateHandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlDateHandingLayout.setVerticalGroup(
            pnlDateHandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        add(pnlDateHanding, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 400, 400));

        javax.swing.GroupLayout pnlTopCincoLayout = new javax.swing.GroupLayout(pnlTopCinco);
        pnlTopCinco.setLayout(pnlTopCincoLayout);
        pnlTopCincoLayout.setHorizontalGroup(
            pnlTopCincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlTopCincoLayout.setVerticalGroup(
            pnlTopCincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        add(pnlTopCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 400, 400));

        btRegresar1.setBackground(new java.awt.Color(102, 102, 102));
        btRegresar1.setFont(new java.awt.Font("Viner Hand ITC", 0, 20)); // NOI18N
        btRegresar1.setForeground(new java.awt.Color(255, 153, 0));
        btRegresar1.setText("Regresar");
        btRegresar1.setActionCommand("0");
        btRegresar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 750, 140, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btRegresar1;
    public javax.swing.JPanel pnlCircularHistorica;
    public javax.swing.JPanel pnlDateHanding;
    public javax.swing.JPanel pnlGrafoBarras;
    public javax.swing.JPanel pnlTopCinco;
    // End of variables declaration//GEN-END:variables
}
