/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author User
 */
public class Fin extends javax.swing.JPanel {

    /**
     * Creates new form Fin
     */
    public Fin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPremio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btTerminar = new javax.swing.JButton();
        lblTipoJuego = new javax.swing.JLabel();
        lblGanadores = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Tipo de Juego:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Premio:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        lblPremio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPremio.setForeground(new java.awt.Color(255, 255, 255));
        add(lblPremio, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, 40));

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Cartones Ganadores");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Felicidades");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        btTerminar.setBackground(new java.awt.Color(102, 102, 102));
        btTerminar.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        btTerminar.setForeground(new java.awt.Color(255, 153, 0));
        btTerminar.setText("Terminar Juego");
        btTerminar.setActionCommand("0");
        btTerminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btTerminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 212, -1));

        lblTipoJuego.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTipoJuego.setForeground(new java.awt.Color(255, 255, 255));
        add(lblTipoJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, 40));

        lblGanadores.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblGanadores.setForeground(new java.awt.Color(255, 255, 255));
        lblGanadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblGanadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 810, 80));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btTerminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel lblGanadores;
    public javax.swing.JLabel lblPremio;
    public javax.swing.JLabel lblTipoJuego;
    // End of variables declaration//GEN-END:variables
}
