/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author User
 */
public class GenerarCartones extends javax.swing.JPanel {

    /**
     * Creates new form GenerarCartones
     */
    public GenerarCartones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btRegresar = new javax.swing.JButton();
        btGenerar = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generar Cartones Bingo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 840, 70));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Cantidad:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 40));

        txtCantidad.setFont(new java.awt.Font("Viner Hand ITC", 0, 20)); // NOI18N
        txtCantidad.setToolTipText("Valor entre 1 y 500");
        txtCantidad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtCantidadActionPerformed(evt);
            }
        });
        add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 300, -1));

        btRegresar.setBackground(new java.awt.Color(102, 102, 102));
        btRegresar.setFont(new java.awt.Font("Viner Hand ITC", 0, 20)); // NOI18N
        btRegresar.setForeground(new java.awt.Color(255, 153, 0));
        btRegresar.setText("Regresar");
        btRegresar.setActionCommand("0");
        btRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 140, -1));

        btGenerar.setBackground(new java.awt.Color(102, 102, 102));
        btGenerar.setFont(new java.awt.Font("Viner Hand ITC", 0, 20)); // NOI18N
        btGenerar.setForeground(new java.awt.Color(255, 153, 0));
        btGenerar.setText("Generar");
        btGenerar.setActionCommand("1");
        btGenerar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btGenerar;
    public javax.swing.JButton btRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
