/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author HP
 */
public class InicioOpcion extends javax.swing.JPanel
{

    /**
     * Creates new form InicioOpcion
     */
    public InicioOpcion()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btSalir = new javax.swing.JButton();
        btEstadisticas = new javax.swing.JButton();
        btVerCarton = new javax.swing.JButton();
        btGenerar = new javax.swing.JButton();
        btEnviarCarton = new javax.swing.JButton();
        btRegistrar = new javax.swing.JButton();
        btIniciar = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setPreferredSize(new java.awt.Dimension(800, 378));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSalir.setText("Salir");
        btSalir.setBorderPainted(false);
        add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 210, 30));

        btEstadisticas.setText("Estadisticas");
        btEstadisticas.setBorderPainted(false);
        add(btEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 210, 30));

        btVerCarton.setText("Ver Carton");
        btVerCarton.setBorderPainted(false);
        add(btVerCarton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 210, 30));

        btGenerar.setText("Generar Cartones");
        btGenerar.setBorderPainted(false);
        add(btGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 210, 30));

        btEnviarCarton.setText("Enviar Carton");
        btEnviarCarton.setBorderPainted(false);
        add(btEnviarCarton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 210, 30));

        btRegistrar.setText("Registrar jugador");
        btRegistrar.setBorderPainted(false);
        add(btRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, 30));

        btIniciar.setText("Iniciar Juego");
        btIniciar.setBorderPainted(false);
        add(btIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 210, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btEnviarCarton;
    public javax.swing.JButton btEstadisticas;
    public javax.swing.JButton btGenerar;
    public javax.swing.JButton btIniciar;
    public javax.swing.JButton btRegistrar;
    public javax.swing.JButton btSalir;
    public javax.swing.JButton btVerCarton;
    // End of variables declaration//GEN-END:variables
}
