/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author HP
 */
public class InicioOpcion extends javax.swing.JPanel
{

    /**
     * Creates new form InicioOpcion
     */
    public InicioOpcion()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btSalir = new javax.swing.JButton();
        btEstadisticas = new javax.swing.JButton();
        btVerCarton = new javax.swing.JButton();
        btGenerar = new javax.swing.JButton();
        btEnviarCarton = new javax.swing.JButton();
        btRegistrar = new javax.swing.JButton();
        btIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(800, 378));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSalir.setBackground(new java.awt.Color(102, 102, 102));
        btSalir.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        btSalir.setForeground(new java.awt.Color(255, 153, 0));
        btSalir.setText("Salir");
        btSalir.setActionCommand("0");
        btSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 270, 40));

        btEstadisticas.setBackground(new java.awt.Color(102, 102, 102));
        btEstadisticas.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        btEstadisticas.setForeground(new java.awt.Color(255, 153, 0));
        btEstadisticas.setText("Estadísticas");
        btEstadisticas.setActionCommand("6");
        btEstadisticas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 270, 40));

        btVerCarton.setBackground(new java.awt.Color(102, 102, 102));
        btVerCarton.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        btVerCarton.setForeground(new java.awt.Color(255, 153, 0));
        btVerCarton.setText("Ver Cartón");
        btVerCarton.setActionCommand("5");
        btVerCarton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btVerCarton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 270, 40));

        btGenerar.setBackground(new java.awt.Color(102, 102, 102));
        btGenerar.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        btGenerar.setForeground(new java.awt.Color(255, 153, 0));
        btGenerar.setText("Generar Cartones");
        btGenerar.setActionCommand("4");
        btGenerar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 270, 40));

        btEnviarCarton.setBackground(new java.awt.Color(102, 102, 102));
        btEnviarCarton.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        btEnviarCarton.setForeground(new java.awt.Color(255, 153, 0));
        btEnviarCarton.setText("Enviar Cartón");
        btEnviarCarton.setActionCommand("3");
        btEnviarCarton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btEnviarCarton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 270, 40));

        btRegistrar.setBackground(new java.awt.Color(102, 102, 102));
        btRegistrar.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        btRegistrar.setForeground(new java.awt.Color(255, 153, 0));
        btRegistrar.setText("Registrar jugador");
        btRegistrar.setActionCommand("2");
        btRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 270, 40));

        btIniciar.setBackground(new java.awt.Color(102, 102, 102));
        btIniciar.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        btIniciar.setForeground(new java.awt.Color(255, 153, 0));
        btIniciar.setText("Iniciar Juego");
        btIniciar.setActionCommand("1");
        btIniciar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 270, 40));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 0, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("B I N G O !");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 36, 500, 330));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btEnviarCarton;
    public javax.swing.JButton btEstadisticas;
    public javax.swing.JButton btGenerar;
    public javax.swing.JButton btIniciar;
    public javax.swing.JButton btRegistrar;
    public javax.swing.JButton btSalir;
    public javax.swing.JButton btVerCarton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
