/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author User
 */
public class RegistroJugador extends javax.swing.JPanel {

    /**
     * Creates new form RegistroJugador
     */
    public RegistroJugador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        btRegistrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btRegresar.setBackground(new java.awt.Color(102, 102, 102));
        btRegresar.setFont(new java.awt.Font("Viner Hand ITC", 0, 20)); // NOI18N
        btRegresar.setForeground(new java.awt.Color(255, 153, 0));
        btRegresar.setText("Regresar");
        btRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(btRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 150, 40));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Jugadores");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 830, 70));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, -1));

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Correo:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 80, -1));

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Cedula:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, -1));

        txtNombre.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNombreActionPerformed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 650, -1));

        txtCorreo.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 650, -1));

        txtCedula.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        txtCedula.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtCedulaActionPerformed(evt);
            }
        });
        add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 230, -1));

        btRegistrar.setBackground(new java.awt.Color(102, 102, 102));
        btRegistrar.setFont(new java.awt.Font("Viner Hand ITC", 0, 20)); // NOI18N
        btRegistrar.setForeground(new java.awt.Color(255, 153, 0));
        btRegistrar.setText("Guardar");
        btRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btRegistrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btRegistrarActionPerformed(evt);
            }
        });
        add(btRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 150, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btRegistrarActionPerformed
    {//GEN-HEADEREND:event_btRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRegistrarActionPerformed

public boolean logInDatosCorrectos(){
        return !((txtNombre.getText()).equals("")&&(txtCorreo.getText()).equals("") && (txtCedula.getText().equals("")));
    }
    
    public void abrirVentanaAnterio(RegistroJugador ventanaAnterior){
        ventanaAnterior.setVisible(true);
    }
    
    public void cancelarIniciarSesion(){
        System.exit(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btRegistrar;
    public javax.swing.JButton btRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
